// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: image.proto

package net.zylklab.nifi.processor.sanbox.auto.protobuf;

public interface ImageListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ImageList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Image image = 1;</code>
   */
  java.util.List<net.zylklab.nifi.processor.sanbox.auto.protobuf.Image> 
      getImageList();
  /**
   * <code>repeated .Image image = 1;</code>
   */
  net.zylklab.nifi.processor.sanbox.auto.protobuf.Image getImage(int index);
  /**
   * <code>repeated .Image image = 1;</code>
   */
  int getImageCount();
  /**
   * <code>repeated .Image image = 1;</code>
   */
  java.util.List<? extends net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageOrBuilder> 
      getImageOrBuilderList();
  /**
   * <code>repeated .Image image = 1;</code>
   */
  net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageOrBuilder getImageOrBuilder(
      int index);
}
