// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: image.proto

package net.zylklab.nifi.processor.sanbox.auto.protobuf;

/**
 * Protobuf type {@code ImageList}
 */
public  final class ImageList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ImageList)
    ImageListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ImageList.newBuilder() to construct.
  private ImageList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ImageList() {
    image_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ImageList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ImageList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              image_ = new java.util.ArrayList<net.zylklab.nifi.processor.sanbox.auto.protobuf.Image>();
              mutable_bitField0_ |= 0x00000001;
            }
            image_.add(
                input.readMessage(net.zylklab.nifi.processor.sanbox.auto.protobuf.Image.PARSER, extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        image_ = java.util.Collections.unmodifiableList(image_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageProtos.internal_static_ImageList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageProtos.internal_static_ImageList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList.class, net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList.Builder.class);
  }

  public static final int IMAGE_FIELD_NUMBER = 1;
  private java.util.List<net.zylklab.nifi.processor.sanbox.auto.protobuf.Image> image_;
  /**
   * <code>repeated .Image image = 1;</code>
   */
  public java.util.List<net.zylklab.nifi.processor.sanbox.auto.protobuf.Image> getImageList() {
    return image_;
  }
  /**
   * <code>repeated .Image image = 1;</code>
   */
  public java.util.List<? extends net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageOrBuilder> 
      getImageOrBuilderList() {
    return image_;
  }
  /**
   * <code>repeated .Image image = 1;</code>
   */
  public int getImageCount() {
    return image_.size();
  }
  /**
   * <code>repeated .Image image = 1;</code>
   */
  public net.zylklab.nifi.processor.sanbox.auto.protobuf.Image getImage(int index) {
    return image_.get(index);
  }
  /**
   * <code>repeated .Image image = 1;</code>
   */
  public net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageOrBuilder getImageOrBuilder(
      int index) {
    return image_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    for (int i = 0; i < getImageCount(); i++) {
      if (!getImage(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < image_.size(); i++) {
      output.writeMessage(1, image_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < image_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, image_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList)) {
      return super.equals(obj);
    }
    net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList other = (net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList) obj;

    if (!getImageList()
        .equals(other.getImageList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getImageCount() > 0) {
      hash = (37 * hash) + IMAGE_FIELD_NUMBER;
      hash = (53 * hash) + getImageList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ImageList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ImageList)
      net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageProtos.internal_static_ImageList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageProtos.internal_static_ImageList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList.class, net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList.Builder.class);
    }

    // Construct using net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getImageFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (imageBuilder_ == null) {
        image_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        imageBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageProtos.internal_static_ImageList_descriptor;
    }

    @java.lang.Override
    public net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList getDefaultInstanceForType() {
      return net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList.getDefaultInstance();
    }

    @java.lang.Override
    public net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList build() {
      net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList buildPartial() {
      net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList result = new net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList(this);
      int from_bitField0_ = bitField0_;
      if (imageBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          image_ = java.util.Collections.unmodifiableList(image_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.image_ = image_;
      } else {
        result.image_ = imageBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList) {
        return mergeFrom((net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList other) {
      if (other == net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList.getDefaultInstance()) return this;
      if (imageBuilder_ == null) {
        if (!other.image_.isEmpty()) {
          if (image_.isEmpty()) {
            image_ = other.image_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureImageIsMutable();
            image_.addAll(other.image_);
          }
          onChanged();
        }
      } else {
        if (!other.image_.isEmpty()) {
          if (imageBuilder_.isEmpty()) {
            imageBuilder_.dispose();
            imageBuilder_ = null;
            image_ = other.image_;
            bitField0_ = (bitField0_ & ~0x00000001);
            imageBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getImageFieldBuilder() : null;
          } else {
            imageBuilder_.addAllMessages(other.image_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      for (int i = 0; i < getImageCount(); i++) {
        if (!getImage(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<net.zylklab.nifi.processor.sanbox.auto.protobuf.Image> image_ =
      java.util.Collections.emptyList();
    private void ensureImageIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        image_ = new java.util.ArrayList<net.zylklab.nifi.processor.sanbox.auto.protobuf.Image>(image_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        net.zylklab.nifi.processor.sanbox.auto.protobuf.Image, net.zylklab.nifi.processor.sanbox.auto.protobuf.Image.Builder, net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageOrBuilder> imageBuilder_;

    /**
     * <code>repeated .Image image = 1;</code>
     */
    public java.util.List<net.zylklab.nifi.processor.sanbox.auto.protobuf.Image> getImageList() {
      if (imageBuilder_ == null) {
        return java.util.Collections.unmodifiableList(image_);
      } else {
        return imageBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Image image = 1;</code>
     */
    public int getImageCount() {
      if (imageBuilder_ == null) {
        return image_.size();
      } else {
        return imageBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Image image = 1;</code>
     */
    public net.zylklab.nifi.processor.sanbox.auto.protobuf.Image getImage(int index) {
      if (imageBuilder_ == null) {
        return image_.get(index);
      } else {
        return imageBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Image image = 1;</code>
     */
    public Builder setImage(
        int index, net.zylklab.nifi.processor.sanbox.auto.protobuf.Image value) {
      if (imageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureImageIsMutable();
        image_.set(index, value);
        onChanged();
      } else {
        imageBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Image image = 1;</code>
     */
    public Builder setImage(
        int index, net.zylklab.nifi.processor.sanbox.auto.protobuf.Image.Builder builderForValue) {
      if (imageBuilder_ == null) {
        ensureImageIsMutable();
        image_.set(index, builderForValue.build());
        onChanged();
      } else {
        imageBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Image image = 1;</code>
     */
    public Builder addImage(net.zylklab.nifi.processor.sanbox.auto.protobuf.Image value) {
      if (imageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureImageIsMutable();
        image_.add(value);
        onChanged();
      } else {
        imageBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Image image = 1;</code>
     */
    public Builder addImage(
        int index, net.zylklab.nifi.processor.sanbox.auto.protobuf.Image value) {
      if (imageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureImageIsMutable();
        image_.add(index, value);
        onChanged();
      } else {
        imageBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Image image = 1;</code>
     */
    public Builder addImage(
        net.zylklab.nifi.processor.sanbox.auto.protobuf.Image.Builder builderForValue) {
      if (imageBuilder_ == null) {
        ensureImageIsMutable();
        image_.add(builderForValue.build());
        onChanged();
      } else {
        imageBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Image image = 1;</code>
     */
    public Builder addImage(
        int index, net.zylklab.nifi.processor.sanbox.auto.protobuf.Image.Builder builderForValue) {
      if (imageBuilder_ == null) {
        ensureImageIsMutable();
        image_.add(index, builderForValue.build());
        onChanged();
      } else {
        imageBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Image image = 1;</code>
     */
    public Builder addAllImage(
        java.lang.Iterable<? extends net.zylklab.nifi.processor.sanbox.auto.protobuf.Image> values) {
      if (imageBuilder_ == null) {
        ensureImageIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, image_);
        onChanged();
      } else {
        imageBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Image image = 1;</code>
     */
    public Builder clearImage() {
      if (imageBuilder_ == null) {
        image_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        imageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Image image = 1;</code>
     */
    public Builder removeImage(int index) {
      if (imageBuilder_ == null) {
        ensureImageIsMutable();
        image_.remove(index);
        onChanged();
      } else {
        imageBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Image image = 1;</code>
     */
    public net.zylklab.nifi.processor.sanbox.auto.protobuf.Image.Builder getImageBuilder(
        int index) {
      return getImageFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Image image = 1;</code>
     */
    public net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageOrBuilder getImageOrBuilder(
        int index) {
      if (imageBuilder_ == null) {
        return image_.get(index);  } else {
        return imageBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Image image = 1;</code>
     */
    public java.util.List<? extends net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageOrBuilder> 
         getImageOrBuilderList() {
      if (imageBuilder_ != null) {
        return imageBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(image_);
      }
    }
    /**
     * <code>repeated .Image image = 1;</code>
     */
    public net.zylklab.nifi.processor.sanbox.auto.protobuf.Image.Builder addImageBuilder() {
      return getImageFieldBuilder().addBuilder(
          net.zylklab.nifi.processor.sanbox.auto.protobuf.Image.getDefaultInstance());
    }
    /**
     * <code>repeated .Image image = 1;</code>
     */
    public net.zylklab.nifi.processor.sanbox.auto.protobuf.Image.Builder addImageBuilder(
        int index) {
      return getImageFieldBuilder().addBuilder(
          index, net.zylklab.nifi.processor.sanbox.auto.protobuf.Image.getDefaultInstance());
    }
    /**
     * <code>repeated .Image image = 1;</code>
     */
    public java.util.List<net.zylklab.nifi.processor.sanbox.auto.protobuf.Image.Builder> 
         getImageBuilderList() {
      return getImageFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        net.zylklab.nifi.processor.sanbox.auto.protobuf.Image, net.zylklab.nifi.processor.sanbox.auto.protobuf.Image.Builder, net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageOrBuilder> 
        getImageFieldBuilder() {
      if (imageBuilder_ == null) {
        imageBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            net.zylklab.nifi.processor.sanbox.auto.protobuf.Image, net.zylklab.nifi.processor.sanbox.auto.protobuf.Image.Builder, net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageOrBuilder>(
                image_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        image_ = null;
      }
      return imageBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ImageList)
  }

  // @@protoc_insertion_point(class_scope:ImageList)
  private static final net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList();
  }

  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<ImageList>
      PARSER = new com.google.protobuf.AbstractParser<ImageList>() {
    @java.lang.Override
    public ImageList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ImageList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ImageList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ImageList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

