// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: image.proto

package net.zylklab.nifi.processor.sanbox.auto.protobuf;

/**
 * Protobuf type {@code Image}
 */
public  final class Image extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Image)
    ImageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Image.newBuilder() to construct.
  private Image(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Image() {
    text_ = com.google.protobuf.ByteString.EMPTY;
    encoded_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Image();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Image(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            label_ = input.readInt64();
            break;
          }
          case 18: {
            bitField0_ |= 0x00000002;
            text_ = input.readBytes();
            break;
          }
          case 26: {
            bitField0_ |= 0x00000004;
            encoded_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageProtos.internal_static_Image_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageProtos.internal_static_Image_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.zylklab.nifi.processor.sanbox.auto.protobuf.Image.class, net.zylklab.nifi.processor.sanbox.auto.protobuf.Image.Builder.class);
  }

  private int bitField0_;
  public static final int LABEL_FIELD_NUMBER = 1;
  private long label_;
  /**
   * <code>required int64 label = 1;</code>
   */
  public boolean hasLabel() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required int64 label = 1;</code>
   */
  public long getLabel() {
    return label_;
  }

  public static final int TEXT_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString text_;
  /**
   * <code>required bytes text = 2;</code>
   */
  public boolean hasText() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required bytes text = 2;</code>
   */
  public com.google.protobuf.ByteString getText() {
    return text_;
  }

  public static final int ENCODED_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString encoded_;
  /**
   * <code>required bytes encoded = 3;</code>
   */
  public boolean hasEncoded() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>required bytes encoded = 3;</code>
   */
  public com.google.protobuf.ByteString getEncoded() {
    return encoded_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasLabel()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasText()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasEncoded()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt64(1, label_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeBytes(2, text_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeBytes(3, encoded_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, label_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, text_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, encoded_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.zylklab.nifi.processor.sanbox.auto.protobuf.Image)) {
      return super.equals(obj);
    }
    net.zylklab.nifi.processor.sanbox.auto.protobuf.Image other = (net.zylklab.nifi.processor.sanbox.auto.protobuf.Image) obj;

    if (hasLabel() != other.hasLabel()) return false;
    if (hasLabel()) {
      if (getLabel()
          != other.getLabel()) return false;
    }
    if (hasText() != other.hasText()) return false;
    if (hasText()) {
      if (!getText()
          .equals(other.getText())) return false;
    }
    if (hasEncoded() != other.hasEncoded()) return false;
    if (hasEncoded()) {
      if (!getEncoded()
          .equals(other.getEncoded())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasLabel()) {
      hash = (37 * hash) + LABEL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLabel());
    }
    if (hasText()) {
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
    }
    if (hasEncoded()) {
      hash = (37 * hash) + ENCODED_FIELD_NUMBER;
      hash = (53 * hash) + getEncoded().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.Image parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.Image parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.Image parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.Image parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.Image parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.Image parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.Image parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.Image parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.Image parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.Image parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.Image parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.Image parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.zylklab.nifi.processor.sanbox.auto.protobuf.Image prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Image}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Image)
      net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageProtos.internal_static_Image_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageProtos.internal_static_Image_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.zylklab.nifi.processor.sanbox.auto.protobuf.Image.class, net.zylklab.nifi.processor.sanbox.auto.protobuf.Image.Builder.class);
    }

    // Construct using net.zylklab.nifi.processor.sanbox.auto.protobuf.Image.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      label_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      text_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      encoded_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.zylklab.nifi.processor.sanbox.auto.protobuf.ImageProtos.internal_static_Image_descriptor;
    }

    @java.lang.Override
    public net.zylklab.nifi.processor.sanbox.auto.protobuf.Image getDefaultInstanceForType() {
      return net.zylklab.nifi.processor.sanbox.auto.protobuf.Image.getDefaultInstance();
    }

    @java.lang.Override
    public net.zylklab.nifi.processor.sanbox.auto.protobuf.Image build() {
      net.zylklab.nifi.processor.sanbox.auto.protobuf.Image result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.zylklab.nifi.processor.sanbox.auto.protobuf.Image buildPartial() {
      net.zylklab.nifi.processor.sanbox.auto.protobuf.Image result = new net.zylklab.nifi.processor.sanbox.auto.protobuf.Image(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.label_ = label_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.text_ = text_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.encoded_ = encoded_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.zylklab.nifi.processor.sanbox.auto.protobuf.Image) {
        return mergeFrom((net.zylklab.nifi.processor.sanbox.auto.protobuf.Image)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.zylklab.nifi.processor.sanbox.auto.protobuf.Image other) {
      if (other == net.zylklab.nifi.processor.sanbox.auto.protobuf.Image.getDefaultInstance()) return this;
      if (other.hasLabel()) {
        setLabel(other.getLabel());
      }
      if (other.hasText()) {
        setText(other.getText());
      }
      if (other.hasEncoded()) {
        setEncoded(other.getEncoded());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasLabel()) {
        return false;
      }
      if (!hasText()) {
        return false;
      }
      if (!hasEncoded()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      net.zylklab.nifi.processor.sanbox.auto.protobuf.Image parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (net.zylklab.nifi.processor.sanbox.auto.protobuf.Image) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long label_ ;
    /**
     * <code>required int64 label = 1;</code>
     */
    public boolean hasLabel() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int64 label = 1;</code>
     */
    public long getLabel() {
      return label_;
    }
    /**
     * <code>required int64 label = 1;</code>
     */
    public Builder setLabel(long value) {
      bitField0_ |= 0x00000001;
      label_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 label = 1;</code>
     */
    public Builder clearLabel() {
      bitField0_ = (bitField0_ & ~0x00000001);
      label_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString text_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>required bytes text = 2;</code>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required bytes text = 2;</code>
     */
    public com.google.protobuf.ByteString getText() {
      return text_;
    }
    /**
     * <code>required bytes text = 2;</code>
     */
    public Builder setText(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      text_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required bytes text = 2;</code>
     */
    public Builder clearText() {
      bitField0_ = (bitField0_ & ~0x00000002);
      text_ = getDefaultInstance().getText();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString encoded_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>required bytes encoded = 3;</code>
     */
    public boolean hasEncoded() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required bytes encoded = 3;</code>
     */
    public com.google.protobuf.ByteString getEncoded() {
      return encoded_;
    }
    /**
     * <code>required bytes encoded = 3;</code>
     */
    public Builder setEncoded(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      encoded_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required bytes encoded = 3;</code>
     */
    public Builder clearEncoded() {
      bitField0_ = (bitField0_ & ~0x00000004);
      encoded_ = getDefaultInstance().getEncoded();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Image)
  }

  // @@protoc_insertion_point(class_scope:Image)
  private static final net.zylklab.nifi.processor.sanbox.auto.protobuf.Image DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.zylklab.nifi.processor.sanbox.auto.protobuf.Image();
  }

  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.Image getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Image>
      PARSER = new com.google.protobuf.AbstractParser<Image>() {
    @java.lang.Override
    public Image parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Image(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Image> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Image> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.zylklab.nifi.processor.sanbox.auto.protobuf.Image getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

