// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: image.proto

package net.zylklab.nifi.processor.sanbox.auto.protobuf;

public final class ImageProtos {
  private ImageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Image_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Image_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImageList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImageList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013image.proto\"5\n\005Image\022\r\n\005label\030\001 \002(\003\022\014\n" +
      "\004text\030\002 \002(\014\022\017\n\007encoded\030\003 \002(\014\"\"\n\tImageLis" +
      "t\022\025\n\005image\030\001 \003(\0132\006.ImageB@\n/net.zylklab." +
      "nifi.processor.sanbox.auto.protobufB\013Ima" +
      "geProtosP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Image_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Image_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Image_descriptor,
        new java.lang.String[] { "Label", "Text", "Encoded", });
    internal_static_ImageList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ImageList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImageList_descriptor,
        new java.lang.String[] { "Image", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
