// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: image.proto

package net.zylklab.nifi.processor.sanbox.auto.protobuf;

public interface ImageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Image)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 label = 1;</code>
   */
  boolean hasLabel();
  /**
   * <code>required int64 label = 1;</code>
   */
  long getLabel();

  /**
   * <code>required bytes text = 2;</code>
   */
  boolean hasText();
  /**
   * <code>required bytes text = 2;</code>
   */
  com.google.protobuf.ByteString getText();

  /**
   * <code>required bytes encoded = 3;</code>
   */
  boolean hasEncoded();
  /**
   * <code>required bytes encoded = 3;</code>
   */
  com.google.protobuf.ByteString getEncoded();
}
