// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow;

public final class ExampleProtos {
  private ExampleProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_Example_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_Example_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_SequenceExample_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_SequenceExample_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rexample.proto\022\ntensorflow\032\rfeature.pro" +
      "to\"1\n\007Example\022&\n\010features\030\001 \001(\0132\024.tensor" +
      "flow.Features\"i\n\017SequenceExample\022%\n\007cont" +
      "ext\030\001 \001(\0132\024.tensorflow.Features\022/\n\rfeatu" +
      "re_lists\030\002 \001(\0132\030.tensorflow.FeatureLists" +
      "B\215\001\n:net.zylklab.nifi.processor.sanbox.a" +
      "uto.protobuf.tensorflowB\rExampleProtosP\001" +
      "Z;github.com/tensorflow/tensorflow/tenso" +
      "rflow/go/core/example\370\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeatureProtos.getDescriptor(),
        });
    internal_static_tensorflow_Example_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_Example_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_Example_descriptor,
        new java.lang.String[] { "Features", });
    internal_static_tensorflow_SequenceExample_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tensorflow_SequenceExample_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_SequenceExample_descriptor,
        new java.lang.String[] { "Context", "FeatureLists", });
    net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeatureProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
