// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow;

public interface ExampleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.Example)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tensorflow.Features features = 1;</code>
   */
  boolean hasFeatures();
  /**
   * <code>.tensorflow.Features features = 1;</code>
   */
  net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Features getFeatures();
  /**
   * <code>.tensorflow.Features features = 1;</code>
   */
  net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeaturesOrBuilder getFeaturesOrBuilder();
}
