// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: feature.proto

package net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow;

public interface FeatureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.Feature)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tensorflow.BytesList bytes_list = 1;</code>
   */
  boolean hasBytesList();
  /**
   * <code>.tensorflow.BytesList bytes_list = 1;</code>
   */
  net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.BytesList getBytesList();
  /**
   * <code>.tensorflow.BytesList bytes_list = 1;</code>
   */
  net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.BytesListOrBuilder getBytesListOrBuilder();

  /**
   * <code>.tensorflow.FloatList float_list = 2;</code>
   */
  boolean hasFloatList();
  /**
   * <code>.tensorflow.FloatList float_list = 2;</code>
   */
  net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FloatList getFloatList();
  /**
   * <code>.tensorflow.FloatList float_list = 2;</code>
   */
  net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FloatListOrBuilder getFloatListOrBuilder();

  /**
   * <code>.tensorflow.Int64List int64_list = 3;</code>
   */
  boolean hasInt64List();
  /**
   * <code>.tensorflow.Int64List int64_list = 3;</code>
   */
  net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Int64List getInt64List();
  /**
   * <code>.tensorflow.Int64List int64_list = 3;</code>
   */
  net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Int64ListOrBuilder getInt64ListOrBuilder();

  public net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Feature.KindCase getKindCase();
}
