// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: feature.proto

package net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow;

public interface FeatureListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.FeatureList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tensorflow.Feature feature = 1;</code>
   */
  java.util.List<net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Feature> 
      getFeatureList();
  /**
   * <code>repeated .tensorflow.Feature feature = 1;</code>
   */
  net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Feature getFeature(int index);
  /**
   * <code>repeated .tensorflow.Feature feature = 1;</code>
   */
  int getFeatureCount();
  /**
   * <code>repeated .tensorflow.Feature feature = 1;</code>
   */
  java.util.List<? extends net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeatureOrBuilder> 
      getFeatureOrBuilderList();
  /**
   * <code>repeated .tensorflow.Feature feature = 1;</code>
   */
  net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeatureOrBuilder getFeatureOrBuilder(
      int index);
}
