// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: feature.proto

package net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow;

public interface FeaturesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.Features)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Map from feature name to feature.
   * </pre>
   *
   * <code>map&lt;string, .tensorflow.Feature&gt; feature = 1;</code>
   */
  int getFeatureCount();
  /**
   * <pre>
   * Map from feature name to feature.
   * </pre>
   *
   * <code>map&lt;string, .tensorflow.Feature&gt; feature = 1;</code>
   */
  boolean containsFeature(
      java.lang.String key);
  /**
   * Use {@link #getFeatureMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Feature>
  getFeature();
  /**
   * <pre>
   * Map from feature name to feature.
   * </pre>
   *
   * <code>map&lt;string, .tensorflow.Feature&gt; feature = 1;</code>
   */
  java.util.Map<java.lang.String, net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Feature>
  getFeatureMap();
  /**
   * <pre>
   * Map from feature name to feature.
   * </pre>
   *
   * <code>map&lt;string, .tensorflow.Feature&gt; feature = 1;</code>
   */

  net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Feature getFeatureOrDefault(
      java.lang.String key,
      net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Feature defaultValue);
  /**
   * <pre>
   * Map from feature name to feature.
   * </pre>
   *
   * <code>map&lt;string, .tensorflow.Feature&gt; feature = 1;</code>
   */

  net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Feature getFeatureOrThrow(
      java.lang.String key);
}
