// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow;

public interface SequenceExampleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.SequenceExample)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tensorflow.Features context = 1;</code>
   */
  boolean hasContext();
  /**
   * <code>.tensorflow.Features context = 1;</code>
   */
  net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Features getContext();
  /**
   * <code>.tensorflow.Features context = 1;</code>
   */
  net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeaturesOrBuilder getContextOrBuilder();

  /**
   * <code>.tensorflow.FeatureLists feature_lists = 2;</code>
   */
  boolean hasFeatureLists();
  /**
   * <code>.tensorflow.FeatureLists feature_lists = 2;</code>
   */
  net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeatureLists getFeatureLists();
  /**
   * <code>.tensorflow.FeatureLists feature_lists = 2;</code>
   */
  net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeatureListsOrBuilder getFeatureListsOrBuilder();
}
