// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow;

/**
 * Protobuf type {@code tensorflow.SequenceExample}
 */
public  final class SequenceExample extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tensorflow.SequenceExample)
    SequenceExampleOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SequenceExample.newBuilder() to construct.
  private SequenceExample(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SequenceExample() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SequenceExample();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SequenceExample(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Features.Builder subBuilder = null;
            if (context_ != null) {
              subBuilder = context_.toBuilder();
            }
            context_ = input.readMessage(net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Features.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(context_);
              context_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeatureLists.Builder subBuilder = null;
            if (featureLists_ != null) {
              subBuilder = featureLists_.toBuilder();
            }
            featureLists_ = input.readMessage(net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeatureLists.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(featureLists_);
              featureLists_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.ExampleProtos.internal_static_tensorflow_SequenceExample_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.ExampleProtos.internal_static_tensorflow_SequenceExample_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample.class, net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample.Builder.class);
  }

  public static final int CONTEXT_FIELD_NUMBER = 1;
  private net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Features context_;
  /**
   * <code>.tensorflow.Features context = 1;</code>
   */
  public boolean hasContext() {
    return context_ != null;
  }
  /**
   * <code>.tensorflow.Features context = 1;</code>
   */
  public net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Features getContext() {
    return context_ == null ? net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Features.getDefaultInstance() : context_;
  }
  /**
   * <code>.tensorflow.Features context = 1;</code>
   */
  public net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeaturesOrBuilder getContextOrBuilder() {
    return getContext();
  }

  public static final int FEATURE_LISTS_FIELD_NUMBER = 2;
  private net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeatureLists featureLists_;
  /**
   * <code>.tensorflow.FeatureLists feature_lists = 2;</code>
   */
  public boolean hasFeatureLists() {
    return featureLists_ != null;
  }
  /**
   * <code>.tensorflow.FeatureLists feature_lists = 2;</code>
   */
  public net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeatureLists getFeatureLists() {
    return featureLists_ == null ? net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeatureLists.getDefaultInstance() : featureLists_;
  }
  /**
   * <code>.tensorflow.FeatureLists feature_lists = 2;</code>
   */
  public net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeatureListsOrBuilder getFeatureListsOrBuilder() {
    return getFeatureLists();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (context_ != null) {
      output.writeMessage(1, getContext());
    }
    if (featureLists_ != null) {
      output.writeMessage(2, getFeatureLists());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (context_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getContext());
    }
    if (featureLists_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getFeatureLists());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample)) {
      return super.equals(obj);
    }
    net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample other = (net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample) obj;

    if (hasContext() != other.hasContext()) return false;
    if (hasContext()) {
      if (!getContext()
          .equals(other.getContext())) return false;
    }
    if (hasFeatureLists() != other.hasFeatureLists()) return false;
    if (hasFeatureLists()) {
      if (!getFeatureLists()
          .equals(other.getFeatureLists())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasContext()) {
      hash = (37 * hash) + CONTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getContext().hashCode();
    }
    if (hasFeatureLists()) {
      hash = (37 * hash) + FEATURE_LISTS_FIELD_NUMBER;
      hash = (53 * hash) + getFeatureLists().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tensorflow.SequenceExample}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tensorflow.SequenceExample)
      net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExampleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.ExampleProtos.internal_static_tensorflow_SequenceExample_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.ExampleProtos.internal_static_tensorflow_SequenceExample_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample.class, net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample.Builder.class);
    }

    // Construct using net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (contextBuilder_ == null) {
        context_ = null;
      } else {
        context_ = null;
        contextBuilder_ = null;
      }
      if (featureListsBuilder_ == null) {
        featureLists_ = null;
      } else {
        featureLists_ = null;
        featureListsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.ExampleProtos.internal_static_tensorflow_SequenceExample_descriptor;
    }

    @java.lang.Override
    public net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample getDefaultInstanceForType() {
      return net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample.getDefaultInstance();
    }

    @java.lang.Override
    public net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample build() {
      net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample buildPartial() {
      net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample result = new net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample(this);
      if (contextBuilder_ == null) {
        result.context_ = context_;
      } else {
        result.context_ = contextBuilder_.build();
      }
      if (featureListsBuilder_ == null) {
        result.featureLists_ = featureLists_;
      } else {
        result.featureLists_ = featureListsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample) {
        return mergeFrom((net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample other) {
      if (other == net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample.getDefaultInstance()) return this;
      if (other.hasContext()) {
        mergeContext(other.getContext());
      }
      if (other.hasFeatureLists()) {
        mergeFeatureLists(other.getFeatureLists());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Features context_;
    private com.google.protobuf.SingleFieldBuilderV3<
        net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Features, net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Features.Builder, net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeaturesOrBuilder> contextBuilder_;
    /**
     * <code>.tensorflow.Features context = 1;</code>
     */
    public boolean hasContext() {
      return contextBuilder_ != null || context_ != null;
    }
    /**
     * <code>.tensorflow.Features context = 1;</code>
     */
    public net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Features getContext() {
      if (contextBuilder_ == null) {
        return context_ == null ? net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Features.getDefaultInstance() : context_;
      } else {
        return contextBuilder_.getMessage();
      }
    }
    /**
     * <code>.tensorflow.Features context = 1;</code>
     */
    public Builder setContext(net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Features value) {
      if (contextBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        context_ = value;
        onChanged();
      } else {
        contextBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.tensorflow.Features context = 1;</code>
     */
    public Builder setContext(
        net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Features.Builder builderForValue) {
      if (contextBuilder_ == null) {
        context_ = builderForValue.build();
        onChanged();
      } else {
        contextBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.tensorflow.Features context = 1;</code>
     */
    public Builder mergeContext(net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Features value) {
      if (contextBuilder_ == null) {
        if (context_ != null) {
          context_ =
            net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Features.newBuilder(context_).mergeFrom(value).buildPartial();
        } else {
          context_ = value;
        }
        onChanged();
      } else {
        contextBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.tensorflow.Features context = 1;</code>
     */
    public Builder clearContext() {
      if (contextBuilder_ == null) {
        context_ = null;
        onChanged();
      } else {
        context_ = null;
        contextBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.tensorflow.Features context = 1;</code>
     */
    public net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Features.Builder getContextBuilder() {
      
      onChanged();
      return getContextFieldBuilder().getBuilder();
    }
    /**
     * <code>.tensorflow.Features context = 1;</code>
     */
    public net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeaturesOrBuilder getContextOrBuilder() {
      if (contextBuilder_ != null) {
        return contextBuilder_.getMessageOrBuilder();
      } else {
        return context_ == null ?
            net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Features.getDefaultInstance() : context_;
      }
    }
    /**
     * <code>.tensorflow.Features context = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Features, net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Features.Builder, net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeaturesOrBuilder> 
        getContextFieldBuilder() {
      if (contextBuilder_ == null) {
        contextBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Features, net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.Features.Builder, net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeaturesOrBuilder>(
                getContext(),
                getParentForChildren(),
                isClean());
        context_ = null;
      }
      return contextBuilder_;
    }

    private net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeatureLists featureLists_;
    private com.google.protobuf.SingleFieldBuilderV3<
        net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeatureLists, net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeatureLists.Builder, net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeatureListsOrBuilder> featureListsBuilder_;
    /**
     * <code>.tensorflow.FeatureLists feature_lists = 2;</code>
     */
    public boolean hasFeatureLists() {
      return featureListsBuilder_ != null || featureLists_ != null;
    }
    /**
     * <code>.tensorflow.FeatureLists feature_lists = 2;</code>
     */
    public net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeatureLists getFeatureLists() {
      if (featureListsBuilder_ == null) {
        return featureLists_ == null ? net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeatureLists.getDefaultInstance() : featureLists_;
      } else {
        return featureListsBuilder_.getMessage();
      }
    }
    /**
     * <code>.tensorflow.FeatureLists feature_lists = 2;</code>
     */
    public Builder setFeatureLists(net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeatureLists value) {
      if (featureListsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        featureLists_ = value;
        onChanged();
      } else {
        featureListsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.tensorflow.FeatureLists feature_lists = 2;</code>
     */
    public Builder setFeatureLists(
        net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeatureLists.Builder builderForValue) {
      if (featureListsBuilder_ == null) {
        featureLists_ = builderForValue.build();
        onChanged();
      } else {
        featureListsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.tensorflow.FeatureLists feature_lists = 2;</code>
     */
    public Builder mergeFeatureLists(net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeatureLists value) {
      if (featureListsBuilder_ == null) {
        if (featureLists_ != null) {
          featureLists_ =
            net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeatureLists.newBuilder(featureLists_).mergeFrom(value).buildPartial();
        } else {
          featureLists_ = value;
        }
        onChanged();
      } else {
        featureListsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.tensorflow.FeatureLists feature_lists = 2;</code>
     */
    public Builder clearFeatureLists() {
      if (featureListsBuilder_ == null) {
        featureLists_ = null;
        onChanged();
      } else {
        featureLists_ = null;
        featureListsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.tensorflow.FeatureLists feature_lists = 2;</code>
     */
    public net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeatureLists.Builder getFeatureListsBuilder() {
      
      onChanged();
      return getFeatureListsFieldBuilder().getBuilder();
    }
    /**
     * <code>.tensorflow.FeatureLists feature_lists = 2;</code>
     */
    public net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeatureListsOrBuilder getFeatureListsOrBuilder() {
      if (featureListsBuilder_ != null) {
        return featureListsBuilder_.getMessageOrBuilder();
      } else {
        return featureLists_ == null ?
            net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeatureLists.getDefaultInstance() : featureLists_;
      }
    }
    /**
     * <code>.tensorflow.FeatureLists feature_lists = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeatureLists, net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeatureLists.Builder, net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeatureListsOrBuilder> 
        getFeatureListsFieldBuilder() {
      if (featureListsBuilder_ == null) {
        featureListsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeatureLists, net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeatureLists.Builder, net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.FeatureListsOrBuilder>(
                getFeatureLists(),
                getParentForChildren(),
                isClean());
        featureLists_ = null;
      }
      return featureListsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tensorflow.SequenceExample)
  }

  // @@protoc_insertion_point(class_scope:tensorflow.SequenceExample)
  private static final net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample();
  }

  public static net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SequenceExample>
      PARSER = new com.google.protobuf.AbstractParser<SequenceExample>() {
    @java.lang.Override
    public SequenceExample parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SequenceExample(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SequenceExample> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SequenceExample> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.zylklab.nifi.processor.sanbox.auto.protobuf.tensorflow.SequenceExample getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

